# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'DemoProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoProject
  pod 'KeychainAccess'

  target 'DemoProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
